### ISSUE TITLE
Unknown "tailwind_merge" filter

### ISSUE THREAD

**Issue by weaverryan** [tales-from-a-dev/flowbite-bundle#17]
Hi!

With #16, I think we just need a little extra tweak :). If I install just this bundle and do nothing else, I'll get:

<img width="347" alt="Screenshot 2023-11-17 at 9 05 17 AM" src="https://github.com/tales-from-a-dev/flowbite-bundle/assets/121003/dbb09847-8f3a-4b62-90d7-c57a58c17e00">

That's because, I believe, even though we install https://github.com/tales-from-a-dev/twig-tailwind-extra, we never register the service for the extension.

One nice DX idea might be: allow `tales-from-a-dev/twig-tailwind-extra` to be a bundle. I mean, it would still be a library that anyone can use. But you also package a tiny bundle class + extension class inside of it that registers this service. Then, Symfony users are all set. An example is Foundry - https://github.com/zenstruck/foundry - the only trick is that the bundle class should live directly in `src/` so that the Flex recipe system can find it. But then you can hide 100% of the other Symfony details in some subdirectory, like `src/Symfony`.

WDYT?

**Comment by weaverryan** [comment]
Oh, also, we need to also register the runtime class :) - `TalesFromADev\Twig\Extra\Tailwind\TailwindRuntime: null`

**Comment by PhilETaylor** [comment]
yup something not quite right after updating here for me also.
![ScreenShot-2023-11-17-15 15 52](https://github.com/tales-from-a-dev/flowbite-bundle/assets/400092/d1a9bfe3-6bba-4ad4-8dd0-0721aa161c41)

**Comment by PhilETaylor** [comment]
Adding the following to my Symfony services.php is enough to get the extension loaded for today

```php
$services->set(TailwindRuntime::class);
$services->set(TailwindExtension::class)->tag('twig.extension');
```

**Comment by ker0x** [comment]
Hello @weaverryan, @PhilETaylor 

I just released new versions for both `flowbite-bundle` and `twig-tailwind-extra` that should fix the problem!

Until symfony/recipes-contrib#1566 is merged, you can add this line into `config/bundles.php`:

```php
// config/bundles.php

return [
    // ...
    TalesFromADev\Twig\Extra\Tailwind\Bridge\Symfony\Bundle\TalesFromADevTwigExtraTailwindBundle::class => ['all' => true],
];

**Comment by PhilETaylor** [comment]
Updated, added class to bundles.php, removed my services from yesterday, and your code works for me like that - thanks.

**Comment by weaverryan** [comment]
It seems to be working for me - thank you for the fast turnaround @ker0x!
